/PROG  MV_RETREAT
/ATTR
DEFAULT_GROUP	= 1,*,*,*,*;
/MN
 : CALL GET_ZONE ;
 : SELECT R[2:zoneID]=1,CALL MV_RETREAT_PICK ;
 :        =2,CALL MV_RETREAT_PLACE ;
 :        =3,CALL MV_RETREAT_HOME ;
 :        ELSE,CALL UNSAFE ;
/POS
/END
