/PROG  MV_PICK
/ATTR
DEFAULT_GROUP	= 1,*,*,*,*;
/MN
 : UFRAME_NUM=${UF_PICK} ;
 : UTOOL_NUM=${UT_PICK} ;
 : J PR{PICK} ${APPROACH_SPEED}% CNT100 Tool_Offset,PR{PICK_APTO} ;
 : L PR{PICK} ${PICK_SPEED}mm/sec CNT0 ;
/POS
/END
