/PROG MV_PLACE
/ATTR
DEFAULT_GROUP	= 1,*,*,*,*;
/MN
 : UFRAME_NUM=${UF_PLACE} ;
 : UTOOL_NUM=${UT_PLACE} ;
 : J PR{PLACE} ${APPROACH_SPEED}% CNT100 Tool_Offset,PR{PLACE_APTO} ;
 : L PR{PLACE} ${PLACE_SPEED}mm/sec CNT0 ;
/POS
/END
