/PROG  MV_RETREAT
/ATTR
DEFAULT_GROUP	= 1,*,*,*,*;
/MN
 : CALL GET_ZONE ;
 : SELECT R{zoneID}=${ZONE_PICK},CALL MV_RETREAT_PICK ;
 :        =${ZONE_PLACE},CALL MV_RETREAT_PLACE ;
 :        =${ZONE_HOME},CALL MV_RETREAT_HOME ;
 :        ELSE,CALL UNSAFE ;
/POS
/END
